name: Test feature branch
'on': pull_request

jobs:
  install-and-test:
    name: 🛠️ Install & Test
    runs-on: ubuntu-latest

    steps:
      - name: 🗜️ Checkout
        uses: actions/checkout@v4

      - name: 🗜️ Setup node version
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: 🛠️ Install
        uses: ./.github/actions/cached-deps

      - name: 📦 Build
        run: yarn build

      - name: 🧪 Run tests
        run: yarn test --collectCoverage --ci

      - name: ⬆️ Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          fail_ci_if_error: true
          verbose: true
          dry_run: true
